In [1]:
import numpy as np

In [2]:
T3 = np.zeros((10,2,3))
print(T3)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


#test training and versions etc..

In [3]:
import accelerate
print(accelerate.__version__)  # Should be 0.26.0 or higher


1.2.0


In [4]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())  # Should return True if GPU is available


2.5.1
True


In [5]:
import torch
print("Using GPU: ", torch.cuda.is_available())
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)


Using GPU:  True


NameError: name 'model' is not defined

In [ ]:
from transformers import TrainingArguments

# Test Trainer integration
training_args = TrainingArguments(
    output_dir="../results",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=4,
    num_train_epochs=1,
    logging_dir="../logs",
    fp16=torch.cuda.is_available(),  # Mixed precision for GPU
)

print("Trainer setup successful!")
